/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package;

import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contraseña");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Confirmar contraseña");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Boton1.setText("Validar contraseñas");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Contraseña encriptada");

        jLabel4.setText("Contraseña desencriptada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Text1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(Text2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(Boton1))
                        .addGap(278, 278, 278)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54)
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Boton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed

        String text = this.Text1.getText();
        String text2 = this.Text2.getText();
        char dato;
        int valor; 
        int a = 1, b = 2, c = 3, d = 4, e = 5, f = 6, g = 7, h = 8, i = 9, j = 10, k = 11, l = 12, m = 13, n = 14, ñ = 15, o = 16, p = 17, q = 18, r = 19, s = 20, t = 21, u = 22, v = 23, w = 24, x = 25, y = 26, z = 27;
    
        if(text.equals(text2) ){
        
        this.Label1.setText("Contraseña valida");
        valor = text2.length();
        int posicion = 0;
        List<Integer> numeros;
        int num = 0;
        String salida ="", salida2 = "";
        numeros = new ArrayList<>();
        List<String> letras;
        letras = new ArrayList<>();
        int descrypt;
        if (valor >= 8 && valor <= 16){
            do{
              dato = text2.charAt(posicion);
              
              if (dato == 'a'){
                  numeros.add(a + 1);
              } else if (dato == 'b') {
                  numeros.add(b - 1);
            } else if (dato == 'c') {
                  numeros.add(c + 1);
            } else if (dato == 'd') {
                  numeros.add(d - 1);
            } else if (dato == 'e') {
                  numeros.add(e + 1);
            } else if (dato == 'f') {
                  numeros.add(f - 1);
            } else if (dato == 'g') {
                  numeros.add(g + 1);
            } else if (dato == 'h') {
                  numeros.add(h - 1);
            } else if (dato == 'i') {
                  numeros.add(i + 1);
            } else if (dato == 'j') {
                  numeros.add(j - 1);
            } else if (dato == 'k') {
                  numeros.add(k + 1);
            } else if (dato == 'l') {
                  numeros.add(l - 1);
            } else if (dato == 'm') {
                  numeros.add(m + 1);
            } else if (dato == 'n') {
                  numeros.add(n - 1);
            } else if (dato == 'ñ') {
                  numeros.add(ñ + 1);
            } else if (dato == 'o') {
                  numeros.add(o - 1);
            } else if (dato == 'p') {
                  numeros.add(p + 1);
            } else if (dato == 'q') {
                  numeros.add(q - 1);
            } else if (dato == 'r') {
                  numeros.add(r + 1);
            } else if (dato == 's') {
                  numeros.add(s - 1);
            } else if (dato == 't') {
                  numeros.add(t + 1);
            } else if (dato == 'u') {
                  numeros.add(u - 1);
            } else if (dato == 'v') {
                  numeros.add(v + 1);
            } else if (dato == 'w') {
                  numeros.add(w - 1);
            } else if (dato == 'x') {
                  numeros.add(x + 1);
            } else if (dato == 'y') {
                  numeros.add(y - 1);
            } else if (dato == 'z') {
                  numeros.add(z + 1);
            }else if(dato == '0'){
                salida2 += "0";
            }else if(dato == '1'){
                salida2 += "1";
            }else if(dato == '2'){
                salida2 += "2";
            }else if(dato == '3'){
                salida2 += "3";
            }else if(dato == '4'){
                salida2 += "4";
            }else if(dato == '5'){
                salida2 += "5";
            }else if(dato == '6'){
                salida2 += "6";
            }else if(dato == '7'){
                salida2 += "7";
            }else if(dato == '8'){
                salida2 += "8";
            }else if(dato == '9'){
                salida2 += "9";
            }
            posicion ++;
            letras.add(String.valueOf(numeros.get(num)));
            salida += letras.get(num);
            descrypt = Integer.parseInt(letras.get(num));
            switch(descrypt){
                case 1: salida2 += "b";
                break;
                case 2: salida2 += "a";
                break;
                case 3: salida2 += "d";
                break;
                case 4: salida2 += "c";
                break;
                case 5: salida2 += "f";
                break;
                case 6: salida2 += "e";
                break;
                case 7: salida2 += "h";
                break;
                case 8: salida2 += "g";
                break;
                case 9: salida2 += "j";
                break;
                case 10: salida2 += "i";
                break;
                case 11: salida2 += "l";
                break;
                case 12: salida2 += "k";
                break;
                case 13: salida2 += "n";
                break;
                case 14: salida2 += "m";
                break;
                case 15: salida2 += "o";
                break;
                case 16: salida2 += "ñ";
                break;
                case 17: salida2 += "q";
                break;
                case 18: salida2 += "p";
                break;
                case 19: salida2 += "s";
                break;
                case 20: salida2 += "r";
                break;
                case 21: salida2 += "u";
                break;
                case 22: salida2 += "t";
                break;
                case 23: salida2 += "w";
                break;
                case 24: salida2 += "v";
                break;
                case 25: salida2 += "y";
                break;
                case 26: salida2 += "x";
                break;
                case 28: salida2 += "z";
                break;
            }
            num++;
            }while(posicion != valor);
            

         this.Label2.setText(salida);
         this.Label3.setText(salida2);
         numeros.clear();
         letras.clear();
         salida = "";
         salida2 = "";
        } else{this.Label1.setText("La contraseña debe tener un minimo de 8 y maximo de 16 caracteres");}
        }
        else {
            this.Label1.setText("Ambas contraseñas deben ser iguales");
        }
    }//GEN-LAST:event_Boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
